services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
      target: development
    container_name: ${PROJECT_NAME:-nest-wallet-api}-dev
    env_file:
      - ../.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT:-3000}:3000"
    working_dir: /usr/src/app
    command: sh deployment/dev-entrypoint.sh
